ARI: 8
ATL: 14
BAL: 10
BOS: 4
CHC: 6
CHW: 3
CIN: 2
CLE: 3
COL: 11
DET: 2
HOU: 8
KCR: 9
LAA: 3
LAD: 2
MIA: 13
MIL: 14
MIN: 14
NYM: 14
NYY: 10
OAK: 3
PHI: 3
PIT: 6
SDP: 4
SEA: 7
SFG: 12
STL: 8
TBR: 9
TEX: 13
TOR: 5
WSN: 12
