ARI: 10
ATL: 15
BAL: 7
BOS: 3
CHC: 4
CHW: 12
CIN: 19
CLE: 20
COL: 27
DET: 8
HOU: 6
KCR: 9
LAA: 3
LAD: 2
MIA: 11
MIL: 19
MIN: 13
NYM: 2
NYY: 5
OAK: 27
PHI: 16
PIT: 2
SDP: 4
SEA: 3
SFG: 2
STL: 6
TBR: 16
TEX: 31
TOR: 5
WSN: 4
